set-option -g history-limit 25000
set -g mouse on

# remap leader key
set -g prefix C-s
bind r source-file ~/.config/tmux/tmux.conf

# vi for copy mode
setw -g mode-keys vi

# status bar
set -g status-right ""
set -g status-style "fg=#a6adc8,bg=#000000"

set -g status-bg default
set -g status-position top
set -g status-interval 1
set -g status-left ""

# rename panes to current working directory
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

set -g default-terminal "tmux-256color"
set -sa terminal-features ",xterm-ghostty:RGB"
