vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.clipboard = 'unnamedplus'
vim.opt.wrap = false
vim.opt.linebreak = true
vim.opt.mouse = 'a'
vim.opt.background = "dark"
vim.opt.termguicolors = true
vim.opt.colorcolumn = "80"
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.softtabstop = -1 -- follow shiftwidth
vim.opt.signcolumn = "yes"
vim.opt.spelllang = { "en_us" }
